site_name: Odin Toolkits Documentation
site_url: https://www.odintoolkits.cn/
site_description: Odin Toolkits Documentation 官方文档网站。Odin Toolkits 是开源的、第三方扩展工具集，主要面向 Odin Inspector and Serializer 的中文用户，提供了一系列实用的工具和功能。
site_author: Yuumix
copyright: Copyright &copy; 2025 Yuumix

# 顶部导航栏右侧的仓库链接
repo_name: OdinToolkits For Unity
repo_url: https://github.com/yuumixcode/OdinToolkits-For-Unity

theme:
  name: material
  # Setup -> colors - 配色方案
  palette:
    - media: "(prefers-color-scheme)" # 根据系统偏好自动切换
      toggle:
        icon: material/brightness-auto
        name: 切换到浅色模式
    - media: "(prefers-color-scheme: light)" # 浅色模式 - mkdocs-material 默认
      scheme: default
      primary: indigo
      accent: light blue
      toggle:
        icon: material/weather-night
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)" # 深色模式 - mkdocs-material 默认
      scheme: slate
      primary: green
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: 自动遵循系统偏好
  font:
    text: Noto Sans SC
    code: Roboto Mono
  language: zh
  logo: https://cdn.jsdelivr.net/gh/yuumixcode/OdinToolkitsDocumentation@main/cdn-assets/logo-color-noshadow.webp
  favicon: https://cdn.jsdelivr.net/gh/yuumixcode/OdinToolkitsDocumentation@main/cdn-assets/logo-color-noshadow.png

  # Overrides
  custom_dir: docs/overrides
  features:
    - content.tooltips # 启用工具提示，如果要 Setup - colors - 配色方案 中的 accent 生效，必须启用此项
    # Setup - navigation - 导航
    - navigation.instant # 即时加载，对于大型文档站点效果更好，必须设置 site_url
    - navigation.instant.progress # 即时加载进度条，仅当页面在 400 毫秒后仍未完成加载时显示
    - navigation.tracking # 锚点追踪，地址栏中的 URL 会自动更新为活动锚点，便于分享
    - navigation.tabs # 顶部标签导航
    - navigation.prune # 导航修剪，对于大型文档站点效果更好，不能与 navigation.expand 一起使用
    - navigation.indexes # 章节索引，让用于分类的目录可以指向一份文档，对于概述非常有用，不能和 toc.integrate 一起使用
    - navigation.top # 立刻返回顶部的按钮
    # ---
    - toc.follow # 锚点跟随，通常是指右侧的目录，启用后会在滚动时自动跟随当前锚点
    # Setup - search - 搜索
    - search.suggest # 搜索建议
    - search.highlight # 搜索高亮
    - search.share # 搜索分享
    # footer
    - navigation.footer

plugins:
  # Setup -> tags
  - tags
  # Setup -> blog
  - blog: # 启用博客功能
      authors_file: "{blog}/.authors.yml"
  # Setup -> search
  - search # 启用搜索功能
  # Document dates 文档日期显示
  - document-dates:
      position: bottom
      type: date
      date_format: "%Y-%m-%d"
      show_author: true

extra_css:
  - https://static.zeoseven.com/zsft/292/main/result.css # 自定义字体-霞鹜文楷
  - extra/stylesheets/customFonts.css # 自定义字体
  - extra/stylesheets/tocStyles.css # TOC目录样式
  - extra/stylesheets/tableStyles.css # 表格样式

markdown_extensions:
  # Admonitions 告诫 ---
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # Annotations 附注 ---
  - attr_list # 按钮需要此模块 ｜ Grids 网格需要此模块 ｜ 表情需要此模块 ｜ 图片需要此模块 ｜ Tooltips 需要此模块
  - md_in_html # Grids 网格需要此模块 ｜ 图片需要此模块
  # 代码高亮 ---
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets # Tooltips 需要此模块
  # 内容栏 ---
  - pymdownx.tabbed:
      alternate_style: true
  # 数据表 ---
  - tables
  # Mermaid 图
  - pymdownx.superfences: # Annotations 附注需要此模块 ｜ 代码高亮需要此模块 ｜ 内容栏需要此模块
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes # 脚注
  # 特殊标记 ---
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # 表情 ---
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list # 定义列表
  - pymdownx.tasklist: # 定义列表
      custom_checkbox: true
  # 图片标题 ---
  - pymdownx.blocks.caption
  # tooltips 提示 ---
  - abbr
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify {} # 锚点链接：统一字符编码，区分大小写

extra:
  alternate:
    - name: 中文
      link: "javascript:translate.changeLanguage('chinese_simplified');"
      lang: zh
    - name: English
      link: "javascript:translate.changeLanguage('english');"
      lang: en
  social:
    - icon: fontawesome/solid/mail-bulk
      link: mailto:<zeriying@gmail.com>
      name: 邮件
    - icon: fontawesome/brands/github
      link: https://github.com/yuumixcode
      name: yuumix code

nav:
  - README: index.md
  - CHANGELOG: CHANGELOG.md
  - 其他说明文档:
      - 许可证声明: LICENSE.md
      - LOGO 图标许可证声明: LOGO-LICENSE.md
      - 贡献指南: CONTRIBUTING.md
  - 使用手册:
      - 脚本文档生成器:
          - 使用指南: contents/manuals/scriptdocgenerator/ScriptDocGeneratorUsage.md
          - 类型解析器支持情况总览: contents/manuals/scriptdocgenerator/TypeAnalysisOverview.md
      - 二级工具模块:
          - 一键生成 SO 工具: contents/manuals/modules/QuickGenerateSO.md
          - 模板代码生成器: contents/manuals/modules/TemplateCodeGen.md
  - 标签总览:
      - blog/tags.md
  - 开发者博客:
      - blog/index.md
  - 关于 Odin Inspector: contents/AboutOdinInspector.md
