# 给定工作流将构建文档页面，适用于 GitHub Actions
name: 构建 MkDocs-Material 页面并推送到 gh-pages 分支 🚀

on:
  push:
    branches:
      - master 
      - main

permissions:
  contents: write

jobs:
  # 第一个工作，名称为 Build MkDocs-Material 页面并推送到 gh-pages 分支
  build:
    name: 构建 MkDocs-Material 页面并推送到 gh-pages 分支
    # runs-on 表示运行在哪里，指 GitHub Actions 服务器的操作系统，使用最新版本的 ubuntu 操作系统
    runs-on: ubuntu-latest
    # 工作流的步骤
    steps:
      - name: 检出并克隆代码库到运行目录
        # uses 表示使用, 使用 GitHub Actions 官方库的 checkout@v4 检出代码库
        uses: actions/checkout@v4
      - name: 配置 Git 凭据，用于推送到 gh-pages 分支
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: 设置 Python 环境
        # 使用 GitHub Actions 官方库的 setup-python@v5 来设置 Python 环境
        uses: actions/setup-python@v5 
        with:
          python-version: '3.x'
      - name: 设置缓存键
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - name: 缓存 MkDocs-Material 依赖
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ github.env.cache_id }}
          path: ~/.cache
          restore-keys: |
            mkdocs-material-
      - name: 安装 MkDocs-Material 的依赖项
        run: |
          pip install mkdocs-material
      - name: 检查当前环境 pip 安装的所有包
        run: |
          pip list
      - name: 构建 MkDocs-Material 页面并推送到 gh-pages 分支
        run: |
          mkdocs gh-deploy --force